# Software

## IBM SPSS Statistics bzw. PSPP

### PSPP: Probleme beim Öffnen von .csv Dateien in MacOS
Wenn du die Fehlermeldung "Could not read the contents of..." bekommst, versuche folgende Lösungen

- Lösche PSPP komplett, und installiere es neu (dazwischen am besten auch den Computer neustarten)
- Importiere die Daten mittels "Drag und Drop"
   - Öffne neben PSPP ein Finder Fenster , und wähle die Datei aus, die du importieren willst (Wichtig! Die Datei *muss* sich in deiner öffentlichen Mappe befinden, sonst bekommt man diesselbe Fehlermeldung)
   - In PSPP, klicke auf "Datei" und dann "Daten importieren" (falls .csv Datei ist)
   - Ziehe  die Datei vom Finder Fenster ins PSPP Fenster
- Gib PSPP manuell Zugriff auf die Festplatte:
   - Schließe PSPP
   - Öffne Systemeinstellungen
   - Geh zur "Sicherheit"
   - Klicke auf "Datenschutz" (rechts oben)
   - Klicke auf "Festplattenvollzugriff" in der linken Liste
   - Mach das Schloss links unten auf
   - Klicke auf "+" und wähle PSPP aus
   - Schließe das Schloss und die Systemeinstellungen


### Dateiformate

`r LINK("https://youtu.be/f7qft7LK6S8")`

Wichtige Datienformate sind

- für **Daten**
    - .sav`r if(lec){" (das SPSS Standard-Datenformat)"}`
    - .csv`r if(lec){" (ein einfacher Text mit [comma separated values](https://en.wikipedia.org/wiki/Comma-separated_values))"}`
- für **Syntax**
    - .sps`r if(lec){" (das SPSS Standard-Syntaxformat)"}`
- für Ausgaben
    - .spv
    
## R
R ist eine frei verfügbare, statistische Programmiersprache.

## Allgemeines
R hat eine sehr aktive onine Community. Bei Fragen führt eine kurze Suche oft zu guten Lösungen -- nutze diese Möglichkeit! Es gibt bereits so viel Einführungsmaterial für R (auch auf Deutsch [@Manderscheid2012]), dass sich dieses Kapitel eigentlich erübrigt. Viele Texte enthalten aber viel zu viele Informationen, die ich für nicht notwendig für die Praxis bzw. den Einstieg in R erachte. Daher möchte ich ganz kurz die wichtigsten Befehle erwähnen; für das "Verstehen" der Inhalte muss aber eventuell in anderen Quellen nachgeschlagen werden.

## Installation & Setup
Neben der Installation von R empfehle ich die Installation von RStudio.

## Packages
Durch packages kann die Funkionalität Rs sehr flexibel erweitert werden. Packages müssen zuerst mit install.packages() installiert werden und können dann mit library() geladen werden.

## Allgemeiner Syntax
- Funktionen werden mit function() augerufen.
    - Innerhalb der Klammer befinden sich dann die Argumente.
- Die Raute wird für Kommentare benutzt
- Zuweisungen erfolgen mit "<-"



